# scale of entire group in arcseconds.  Currently this
# is a gaussian sigma
cluster_scale: 4.0
dims: [96,96]
nobj: 8
pixel_scale: 0.263

noise_sigma: 0.04
psf_noise_sigma: 0.0001

nband: 1

pdfs:
    g:
        sigma: 0.2

    hlr:
        type: lognormal
        mean: 0.5
        sigma: 0.15

    F:
        # track the half light radius
        type: track_hlr
        factor: 100.0

    disk:
        color: [1.0]

    bulge:
        color: [1.0]

        # g_bulge=g_fac*g_disk
        g_fac:
            type: uniform
            range: [0.5, 1.0]


        fracdev:
            type: uniform
            range: [0.0, 1.0]

        # bulge_hlr=hlr_fac*disk_hlr
        hlr_fac: 
            type: uniform
            range: [0.9, 1.1]

        # shift in units of the disk hlr
        bulge_shift: 0.05

    knots:
        color: [1.0]

        num:
            type: uniform
            range: [1, 100]


        # flux per knot as a fraction of the disk flux
        # so 100 knots would have a total of 1/10 the disk flux
        flux_frac_per_knot: 0.001


fit_model: bdf
