# scale of entire group in arcseconds.  Currently this
# is a gaussian sigma
cluster_scale: 2.0
dims: [64,64]
nobj: 4
pixel_scale: 0.263

noise_sigma: 0.04
psf_noise_sigma: 0.0001

nband: 3

pdfs:
    g:
        sigma: 0.2

    # hlr of the disk
    hlr:
        type: lognormal
        mean: 0.5
        sigma: 0.15

    F:
        # track the half light radius
        type: track_hlr
        factor: 100.0

    disk:
        color: [1.25, 1.0, 0.75]

    bulge:
        # relative to disk
        g:
            fac:
                type: uniform
                rng: [0.5, 1.0]

        color: [0.5, 1.0, 1.5]
        fracdev:
            type: uniform
            range: [0.0, 1.0]

        hlr_fac: 
            type: uniform
            # relative to disk size
            range: [0.9, 1.1]

        # shift in units of the disk hlr
        bulge_shift: 0.05

    knots:
        num:
            type: uniform
            range: [1, 100]

        color: [1.5, 1.0, 0.5]

        # flux per knot as a fraction of the disk flux
        flux_frac_per_knot: 0.001


fit_model: bdf
