dims: [48, 48]
#dims: [64, 64]
nobj: 16
#models: ['gauss','exp','dev']
models: ['exp','dev']

noise_sigma: 0.01
#noise_sigma: 0.001
psf_dims: [25,25]
psf_noise_sigma: 0.0001

pdfs:
    g:
        sigma: 0.2
    T:
        mean: 16.0
        sigma: 2.0
    F:
        mean: 2.0
        sigma: 2.0

fit_model: "dev"
