dims: [48, 48]
nobj: 1
models: ["dev"]
noise_sigma: 0.01
psf_dims: [25,25]
psf_noise_sigma: 0.0001

pdfs:
    g:
        sigma: 0.2
    T:
        type: normal
        mean: 100.0
        sigma: 1.0
        limits: [0,200]

    F:
        mean: 2.0
        sigma: 0.01

fit_model: "dev"
