dims: [32, 32]
nobj: 2
models: ["dev"]
noise_sigma: 0.01
psf_dims: [25,25]
psf_noise_sigma: 0.0001

pdfs:
    g:
        sigma: 0.2
    T:
        mean: 16.0
        sigma: 2.0

    F:
        mean: 2.0
        sigma: 2.0


fit_model: "gauss"
