dims: [128, 128]
nobj: 48
models: ['gauss','exp','dev']

noise_sigma: 0.01
#noise_sigma: 0.001
psf_dims: [25,25]
psf_noise_sigma: 0.0001

pdfs:
    g:
        sigma: 0.2
    T:
        mean: 16.0
        sigma: 2.0
        limits: [0,100]
    F:
        mean: 2.0
        sigma: 2.0

fit_model: "gauss"
